connected:
  image: pdxjohnny/freeze-tool
  command: /freeze-tool/run connected
  privileged: true
  volumes:
    - "/dev/bus/usb:/dev/bus/usb"
  environment:
    - FREEZETOOL_HOST=web
  links:
   - web

web:
  image: pdxjohnny/freeze-tool
  command: /freeze-tool/run web
  ports:
    - "7777:7777"
