FROM pdxjohnny/gox

ENV GOPATH /go/src/github.com/pdxjohnny/freeze-tool/Godeps/_workspace:/go
ENV USER root

WORKDIR /go/src/github.com/pdxjohnny/freeze-tool

ADD . /go/src/github.com/pdxjohnny/freeze-tool
