history:
  image: pdxjohnny/freeze-tool
  command: /freeze-tool/run history
  environment:
    - FREEZETOOL_HOST=web
  links:
   - web

web:
  image: pdxjohnny/freeze-tool
  command: /freeze-tool/run web
  ports:
    - "7777:7777"
